name: LaTeX build
on:
  push:
    branches-ignore:
      - 'gh-action-result/pdflatex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile the presentation
        uses: xu-cheng/latex-action@v2
        with:
          root_file: presentation.tex
          latexmk_shell_escape: true
      - name: Compile the proceedings
        uses: xu-cheng/latex-action@v2
        with:
          root_file: proceedings.tex
          latexmk_shell_escape: true
      - name: Commit to orphan branch
        run: |
          git checkout --orphan gh-action-result/pdflatex
          git rm -rf .
          git checkout master README.md
          git add presentation.pdf proceedings.pdf README.md
          git -c user.name='GitHub Action' -c user.email='action@github.com' commit -m "Built paper"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-action-result/pdflatex
          force: true